insert into client(id,name,height,picture_url) values('1','Justyna Grabowska',188,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('2','Dominika Andrzejewska',170,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('3','Małgorzata Adamska',181,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('4','dr Ernest Marciniak',152,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('5','Stefan Kalinowski',156,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('6','mgr dr Dawid Czarnecki',159,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('7','doc. dr Elżbieta Maciejewska',186,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('8','mgr Grzegorz Wróblewski',161,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('9','Klaudia Borowska',186,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('10','dr doc. Olgierd Mazurek',175,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('11','doc. Olgierd Sawicki',173,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('12','mgr Robert Wróblewski',151,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('13','dr Magdalena Mróz',163,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('14','Lidia Brzezińska',154,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('15','inż. Alex Zakrzewski',153,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('16','Stefan Witkowski',185,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('17','Matylda Zielińska',154,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('18','doc. inż. Aleksandra Włodarczyk',182,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('19','Piotr Brzeziński',184,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('20','Paulina Zając',185,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('21','mgr dr Andrzej Marciniak',178,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('22','Julianna Borkowska',185,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('23','doc. Daria Szewczyk',156,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('24','Dominika Mazurek',156,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('25','Bianka Borowska',160,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('26','Liwia Pawłowska',161,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('27','Albert Witkowski',178,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('28','Hanna Pietrzak',157,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('29','inż. Tymon Baranowski',187,'https://thispersondoesnotexist.com/image');
insert into client(id,name,height,picture_url) values('30','Urszula Kołodziej',183,'https://thispersondoesnotexist.com/image');
