insert into coach(id,name,"pictureUrl") values('1','Liwia Zając','https://api-wwh.codevillains.me/assets/1.jpg');
insert into coach(id,name,"pictureUrl") values('2','Eliza Kamińska','https://api-wwh.codevillains.me/assets/2.jpg');
insert into coach(id,name,"pictureUrl") values('3','inż. Przemysław Adamczyk','https://api-wwh.codevillains.me/assets/3.jpg');
insert into coach(id,name,"pictureUrl") values('4','Fryderyk Jaworski','https://api-wwh.codevillains.me/assets/4.jpg');
insert into coach(id,name,"pictureUrl") values('5','Julita Błaszczyk','https://api-wwh.codevillains.me/assets/5.jpg');
insert into coach(id,name,"pictureUrl") values('6','dr Mieszko Pietrzak','https://api-wwh.codevillains.me/assets/6.jpg');
insert into coach(id,name,"pictureUrl") values('7','Natalia Kalinowska','https://api-wwh.codevillains.me/assets/7.jpg');
insert into coach(id,name,"pictureUrl") values('8','Sonia Kalinowska','https://api-wwh.codevillains.me/assets/8.jpg');
insert into coach(id,name,"pictureUrl") values('9','Ernest Zawadzki','https://api-wwh.codevillains.me/assets/9.jpg');
insert into coach(id,name,"pictureUrl") values('10','Józef Adamski','https://api-wwh.codevillains.me/assets/10.jpg');
insert into coach(id,name,"pictureUrl") values('11','Tadeusz Pietrzak','https://api-wwh.codevillains.me/assets/11.jpg');
insert into coach(id,name,"pictureUrl") values('12','Katarzyna Rutkowska','https://api-wwh.codevillains.me/assets/12.jpg');
insert into coach(id,name,"pictureUrl") values('13','Joanna Kubiak','https://api-wwh.codevillains.me/assets/13.jpg');
insert into coach(id,name,"pictureUrl") values('14','Adam Nowicki','https://api-wwh.codevillains.me/assets/14.jpg');
insert into coach(id,name,"pictureUrl") values('15','Kornelia Rutkowska','https://api-wwh.codevillains.me/assets/15.jpg');
insert into coach(id,name,"pictureUrl") values('16','Arkadiusz Borowski','https://api-wwh.codevillains.me/assets/16.jpg');
insert into coach(id,name,"pictureUrl") values('17','Izabela Piotrowska','https://api-wwh.codevillains.me/assets/17.jpg');
insert into coach(id,name,"pictureUrl") values('18','Cyprian Walczak','https://api-wwh.codevillains.me/assets/18.jpg');
insert into coach(id,name,"pictureUrl") values('19','Cezary Cieślak','https://api-wwh.codevillains.me/assets/19.jpg');
insert into coach(id,name,"pictureUrl") values('20','Gustaw Grabowski','https://api-wwh.codevillains.me/assets/20.jpg');
insert into coach(id,name,"pictureUrl") values('21','Apolonia Błaszczyk','https://api-wwh.codevillains.me/assets/21.jpg');
insert into coach(id,name,"pictureUrl") values('22','Anna Rutkowska','https://api-wwh.codevillains.me/assets/22.jpg');
insert into coach(id,name,"pictureUrl") values('23','Oliwia Pietrzak','https://api-wwh.codevillains.me/assets/23.jpg');
insert into coach(id,name,"pictureUrl") values('24','Sylwia Zakrzewska','https://api-wwh.codevillains.me/assets/24.jpg');
insert into coach(id,name,"pictureUrl") values('25','mgr Katarzyna Wojciechowska','https://api-wwh.codevillains.me/assets/25.jpg');
insert into coach(id,name,"pictureUrl") values('26','Dawid Laskowski','https://api-wwh.codevillains.me/assets/26.jpg');
insert into coach(id,name,"pictureUrl") values('27','dr Kalina Andrzejewska','https://api-wwh.codevillains.me/assets/27.jpg');
insert into coach(id,name,"pictureUrl") values('28','Julia Michalak','https://api-wwh.codevillains.me/assets/28.jpg');
insert into coach(id,name,"pictureUrl") values('29','Kalina Baranowska','https://api-wwh.codevillains.me/assets/29.jpg');
insert into coach(id,name,"pictureUrl") values('30','Zuzanna Piotrowska','https://api-wwh.codevillains.me/assets/30.jpg');
