insert into coach(id,name,"pictureUrl") values('1','Liwia Zając','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('2','Eliza Kamińska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('3','inż. Przemysław Adamczyk','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('4','Fryderyk Jaworski','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('5','Julita Błaszczyk','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('6','dr Mieszko Pietrzak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('7','Natalia Kalinowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('8','Sonia Kalinowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('9','Ernest Zawadzki','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('10','Józef Adamski','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('11','Tadeusz Pietrzak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('12','Katarzyna Rutkowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('13','Joanna Kubiak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('14','Adam Nowicki','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('15','Kornelia Rutkowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('16','Arkadiusz Borowski','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('17','Izabela Piotrowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('18','Cyprian Walczak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('19','Cezary Cieślak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('20','Gustaw Grabowski','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('21','Apolonia Błaszczyk','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('22','Anna Rutkowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('23','Oliwia Pietrzak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('24','Sylwia Zakrzewska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('25','mgr Katarzyna Wojciechowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('26','Dawid Laskowski','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('27','dr Kalina Andrzejewska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('28','Julia Michalak','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('29','Kalina Baranowska','https://thispersondoesnotexist.com/');
insert into coach(id,name,"pictureUrl") values('30','Zuzanna Piotrowska','https://thispersondoesnotexist.com/');