version: "3.2"

services:
  backend:
    image: supernovaunwired/whitewolf-hackathon-backend:0.31
    ports:
      - "8080:8080"
      - "8090:8090"
    restart: always
    environment:
      PRIVATE_KEY_PATH: /keys/private.der
      PUBLIC_KEY_PATH: /keys/public.der
      APP_SECRET: "😄"
    volumes:
      - type: bind
        source: /root/keys
        target: /keys
        read_only: true

      - type: bind
        source: /root/assets
        target: /assets
        read_only: false

  frontend:
    image: porcupine96/peak-gym-frontend:0.7
    ports:
      - "3000:80"
    restart: always

  postgres:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db_name
