version: "3.2"

services:
  backend:
    image: supernovaunwired/whitewolf-hackathon-backend:0.1
    ports:
      - "8080:8080"
    restart: always
    environment:
      PRIVATE_KEY_PATH: /keys/private.der
      PUBLIC_KEY_PATH: /keys/public.der
    volumes:
      - type: bind
        source: /root/keys
        target: /keys
        read_only: true

  postgres:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: db_name
